# Generated by Django 4.0 on 2021-12-29 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорію',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва товару')),
                ('image', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('description', models.TextField(verbose_name='Опис продукту')),
                ('price', models.CharField(max_length=10, verbose_name='Ціна')),
                ('discounted_price', models.CharField(max_length=10, verbose_name='Ціна зі знижкою')),
                ('number', models.CharField(max_length=10, verbose_name='Кількість')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.productcategory')),
            ],
            options={
                'verbose_name': 'Тавару',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
