# Generated by Django 4.0 on 2021-12-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(default=0, max_length=3, verbose_name='Ціна зі знижкою'),
            preserve_default=False,
        ),
    ]
