# Generated by Django 4.0 on 2021-12-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_discounted_price_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(max_length=3, verbose_name='Знижка'),
        ),
    ]
