# Generated by Django 4.0 on 2022-01-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_productcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.CharField(default=0, max_length=20, verbose_name='Ціна зі знижкою'),
        ),
    ]
