# Generated by Django 4.0 on 2022-01-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.IntegerField(max_length=10, verbose_name='Кількість'),
        ),
    ]
