# Generated by Django 4.0 on 2022-01-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(default=0, max_length=20, verbose_name='Ціна зі знижкою'),
        ),
    ]
