# Generated by Django 4.0 on 2022-01-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_basket_options_reviewsproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsproduct',
            name='reviews',
            field=models.TextField(max_length=200, verbose_name='Відгук'),
        ),
    ]
