# Generated by Django 4.0 on 2022-01-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mail_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
